orgs:
    hosts:
        merkaba:
            ansible_host: 34.82.111.200
            ansible_user: tesseract
cas:
    hosts:
        ca_merkaba:
            ansible_host: 34.82.111.200
            ansible_user: tesseract
        ca_visa:
            ansible_host: 34.82.111.200
            ansible_user: ubuntu
