#!/bin/bash

function createMerkaba() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/merkaba.cooperativa.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-merkaba --tls.certfiles "${PWD}/organizations/fabric-ca/merkaba/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-merkaba.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-merkaba.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-merkaba.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-merkaba.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy merkaba's CA cert to merkaba's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/merkaba/ca-cert.pem" "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/msp/tlscacerts/ca.crt"

  # Copy merkaba's CA cert to merkaba's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/merkaba/ca-cert.pem" "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/tlsca/tlsca.merkaba.cooperativa.com-cert.pem"

  # Copy merkaba's CA cert to merkaba's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/ca"
  cp "${PWD}/organizations/fabric-ca/merkaba/ca-cert.pem" "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/ca/ca.merkaba.cooperativa.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-merkaba --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/merkaba/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-merkaba --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/merkaba/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-merkaba --id.name merkabaadmin --id.secret merkabaadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/merkaba/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-merkaba -M "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/peers/peer0.merkaba.cooperativa.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/merkaba/ca-cert.pem"
  { set +x; } 2>/dev/null
  # Aquí me quedé:
  cp "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/peers/peer0.merkaba.cooperativa.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-merkaba -M "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/peers/peer0.merkaba.cooperativa.com/tls" --enrollment.profile tls --csr.hosts peer0.merkaba.cooperativa.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/merkaba/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/peers/peer0.merkaba.cooperativa.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/peers/peer0.merkaba.cooperativa.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/peers/peer0.merkaba.cooperativa.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/peers/peer0.merkaba.cooperativa.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/peers/peer0.merkaba.cooperativa.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/peers/peer0.merkaba.cooperativa.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-merkaba -M "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/users/User1@merkaba.cooperativa.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/merkaba/ca-cert.pem"
  { set +x; } 2>/dev/null
  # No se pudo ejecutar
  cp "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/users/User1@merkaba.cooperativa.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://merkabaadmin:merkabaadminpw@localhost:7054 --caname ca-merkaba -M "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/users/Admin@merkaba.cooperativa.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/merkaba/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/merkaba.cooperativa.com/users/Admin@merkaba.cooperativa.com/msp/config.yaml"
}

function createVisa() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/visa.cooperativa.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/visa.cooperativa.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-visa --tls.certfiles "${PWD}/organizations/fabric-ca/visa/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-visa.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-visa.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-visa.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-visa.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy visa's CA cert to visa's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/visa/ca-cert.pem" "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/msp/tlscacerts/ca.crt"

  # Copy visa's CA cert to visa's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/visa/ca-cert.pem" "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/tlsca/tlsca.visa.cooperativa.com-cert.pem"

  # Copy visa's CA cert to visa's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/ca"
  cp "${PWD}/organizations/fabric-ca/visa/ca-cert.pem" "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/ca/ca.visa.cooperativa.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-visa --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/visa/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-visa --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/visa/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-visa --id.name visaadmin --id.secret visaadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/visa/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-visa -M "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/peers/peer0.visa.cooperativa.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/visa/ca-cert.pem"
  { set +x; } 2>/dev/null

  # No se puede:
  cp "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/peers/peer0.visa.cooperativa.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-visa -M "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/peers/peer0.visa.cooperativa.com/tls" --enrollment.profile tls --csr.hosts peer0.visa.cooperativa.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/visa/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/peers/peer0.visa.cooperativa.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/peers/peer0.visa.cooperativa.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/peers/peer0.visa.cooperativa.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/peers/peer0.visa.cooperativa.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/peers/peer0.visa.cooperativa.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/peers/peer0.visa.cooperativa.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-visa -M "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/users/User1@visa.cooperativa.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/visa/ca-cert.pem"
  { set +x; } 2>/dev/null

  # No se puede:
  cp "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/users/User1@visa.cooperativa.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://visaadmin:visaadminpw@localhost:8054 --caname ca-visa -M "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/users/Admin@visa.cooperativa.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/visa/ca-cert.pem"
  { set +x; } 2>/dev/null

  # No se puede:
  cp "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/visa.cooperativa.com/users/Admin@visa.cooperativa.com/msp/config.yaml"
}

function createSocio1() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/socio1.cooperativa.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname ca-socio1 --tls.certfiles "${PWD}/organizations/fabric-ca/socio1/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-socio1.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-socio1.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-socio1.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-socio1.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy socio1's CA cert to socio1's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/socio1/ca-cert.pem" "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/msp/tlscacerts/ca.crt"

  # Copy socio1's CA cert to socio1's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/socio1/ca-cert.pem" "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/tlsca/tlsca.socio1.cooperativa.com-cert.pem"

  # Copy socio1's CA cert to socio1's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/ca"
  cp "${PWD}/organizations/fabric-ca/socio1/ca-cert.pem" "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/ca/ca.socio1.cooperativa.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-socio1 --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/socio1/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-socio1 --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/socio1/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-socio1 --id.name socio1admin --id.secret socio1adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/socio1/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-socio1 -M "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/peers/peer0.socio1.cooperativa.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/socio1/ca-cert.pem"
  { set +x; } 2>/dev/null
  
  # No se puede:
  cp "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/peers/peer0.socio1.cooperativa.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-socio1 -M "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/peers/peer0.socio1.cooperativa.com/tls" --enrollment.profile tls --csr.hosts peer0.socio1.cooperativa.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/socio1/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/peers/peer0.socio1.cooperativa.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/peers/peer0.socio1.cooperativa.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/peers/peer0.socio1.cooperativa.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/peers/peer0.socio1.cooperativa.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/peers/peer0.socio1.cooperativa.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/peers/peer0.socio1.cooperativa.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:10054 --caname ca-socio1 -M "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/users/User1@socio1.cooperativa.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/socio1/ca-cert.pem"
  { set +x; } 2>/dev/null

  # No se puede:
  cp "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/users/User1@socio1.cooperativa.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://socio1admin:socio1adminpw@localhost:10054 --caname ca-socio1 -M "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/users/Admin@socio1.cooperativa.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/socio1/ca-cert.pem"
  { set +x; } 2>/dev/null

  # No se puede:
  cp "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/socio1.cooperativa.com/users/Admin@socio1.cooperativa.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/cooperativa.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/cooperativa.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/cooperativa.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/cooperativa.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/cooperativa.com/msp/tlscacerts/tlsca.cooperativa.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/cooperativa.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/cooperativa.com/tlsca/tlsca.cooperativa.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/cooperativa.com/orderers/orderer.cooperativa.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # No se puede:
  cp "${PWD}/organizations/ordererOrganizations/cooperativa.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/cooperativa.com/orderers/orderer.cooperativa.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/cooperativa.com/orderers/orderer.cooperativa.com/tls" --enrollment.profile tls --csr.hosts orderer.cooperativa.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/cooperativa.com/orderers/orderer.cooperativa.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/cooperativa.com/orderers/orderer.cooperativa.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/cooperativa.com/orderers/orderer.cooperativa.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/cooperativa.com/orderers/orderer.cooperativa.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/cooperativa.com/orderers/orderer.cooperativa.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/cooperativa.com/orderers/orderer.cooperativa.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/cooperativa.com/orderers/orderer.cooperativa.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/cooperativa.com/orderers/orderer.cooperativa.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/cooperativa.com/orderers/orderer.cooperativa.com/msp/tlscacerts/tlsca.cooperativa.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/cooperativa.com/users/Admin@cooperativa.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # No se puede:
  cp "${PWD}/organizations/ordererOrganizations/cooperativa.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/cooperativa.com/users/Admin@cooperativa.com/msp/config.yaml"
}
