# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'
services:
  peer0.merkaba.cooperativa.com:
    container_name: peer0.merkaba.cooperativa.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=cooperativa
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - /var/run/docker.sock:/host/var/run/docker.sock

  peer0.visa.cooperativa.com:
    container_name: peer0.visa.cooperativa.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=cooperativa
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - /var/run/docker.sock:/host/var/run/docker.sock

  peer0.socio1.cooperativa.com:
    container_name: peer0.socio1.cooperativa.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=cooperativa
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - /var/run/docker.sock:/host/var/run/docker.sock