# - name: Ping my hosts
#   ansible.builtin.ping:

# - name: Print message
#   ansible.builtin.debug:
#    msg: Hello world

# - name: Crear un archivo de texto con "Hola mundo"
#   copy:
#    content: "Hola mundo desde deploy_cas"
#    dest: /home/tesseract/hola_mundo.txt

---
- name: Crear directorio para Docker Compose en el nodo remoto
  file:
    path: /opt/merkaba-ca/merkaba
    state: directory
  tags: 
    - set-docker-directory

- name: Copiar archivo de configuración merkaba/fabric-ca-server-config.yaml al nodo remoto
  copy:
    src: /home/tesseract/merkaba-dispersed/ansible/roles/deploy_cas/files/config/merkaba/fabric-ca-server-config.yaml
    dest: /opt/merkaba-ca/merkaba/fabric-ca-server-config.yaml
  tags: 
    - copy-ca-config-file

- name: Copiar archivo docker-compose compose-ca-merkaba.yaml al nodo remoto
  copy:
    src: /home/tesseract/merkaba-dispersed/ansible/roles/deploy_cas/files/compose/compose-ca-merkaba.yaml
    dest: /opt/merkaba-ca/merkaba/docker-compose.yaml
  tags: 
    - copy-ca-docker-compose

- name: Desplegar el contenedor de merkaba-ca usando Docker Compose
  command: docker-compose -f /opt/merkaba-ca/merkaba/docker-compose.yaml up -d
  args:
    chdir: /opt/merkaba-ca/merkaba
  tags: 
    - deploy-ca-docker-compose